version: '3'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"

    environment:
      - CHOKIDAR_USEPOLLING=true # 👈 importante para hot-reload en Docker
      - PORT=3000
    restart: always