version: '3'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"

    environment:
      - CHOKIDAR_USEPOLLING=true # 👈 importante para hot-reload en Docker
      - PORT=3000
      - HOST=0.0.0.0              # 👈 esto es clave para que React escuche fuera del contenedor
    restart: always